name: ci
on: [push, pull_request]
jobs:
  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rustc || 'stable' }} ${{ matrix.extra_desc }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure || false }}
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            rustc: 1.43.0
            extra_desc: dist-server
            extra_args: --no-default-features --features=dist-tests test_dist_ -- --test-threads 1
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Install rust
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: ${{ matrix.rustc }}

      - name: Build tests
        run: cargo test --no-run --locked --all-targets --verbose ${{ matrix.extra_args }}

      - name: Run tests
        run: cargo test --locked --all-targets --verbose ${{ matrix.extra_args }}